---
title: "Matrices I"
subtitle: Linear Algebra and Programming Skills
author: "Dr Jon Shiach"
format:
  revealjs:
    slide-level: 3
    transition: slide
    navigation-mode: vertical
    theme: [default, custom.scss]
    controls-layout: bottom-right
    controls-tutorial: true
    smaller: true
    presentation-h2-font-size: 0.5em
---

# Matrices

A matrix is a rectangular array of elements which can be numbers, mathematical expressions, symbols, or even other matrices

$$ \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix} $$

This matrix contains 6 elements arranged in 2 (horizontal) rows and 3 (vertical) columns

Alternative representations of matrices include using square brackets or even no brackets at all (not recommended)

\begin{align*}
    &\begin{bmatrix} 
        1 & 2 & 3  \\
        4 & 5 & 6 
    \end{bmatrix}, 
    &
    &\begin{matrix} 
        1 & 2 & 3  \\
        4 & 5 & 6 
    \end{matrix} 
\end{align*}

Matrices are usually represented using uppercase characters

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$$

# Dimensions of a Matrix

The dimension or size of a matrix is expressed using $m \times n$ where $m$ and $n$ are the number of rows and columns of the matrix respectively.

\begin{align*}
    \begin{matrix} \leftarrow & \text{columns} & \rightarrow \end{matrix}\\
    \begin{matrix}
        \uparrow \\ \text{rows} \\ \downarrow
    \end{matrix}
    \begin{pmatrix}
        \square & \square & \cdots & \square \\
        \square & \square & \cdots & \square \\
        \vdots & \vdots & \ddots & \vdots \\
        \square & \square & \cdots & \square 
    \end{pmatrix}
\end{align*}

For example, given the matrices 

$$A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, B = \begin{pmatrix} a & b \\ c & d \\ e & f \end{pmatrix}, C = \begin{pmatrix} x & y & z & w \end{pmatrix}, D = \begin{pmatrix} \alpha & \beta & \gamma \\ \delta & \epsilon & \zeta \end{pmatrix}$$

we see that $A$ is a $2\times 2$ matrix, $B$ is a $3 \times 2$ matrix, $C$ is a $1 \times 4$ matrix and $D$ is a $2 \times 3$ matrix.

# Matrix Indexing

Individual elements of a matrix are **indexed** using subscripts, $a_{ij}$, where $i$ is the **row** number and $j$ is the **column** number

For example, given the matrix 

$$A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$$

then $a_{11} = 1$, $a_{12} = 2$, $a_{21} = 3$ and $a_{22} = 4$

Some alternative notation used for matrix indexing are

$$ a_{ij} = [A]_{ij} = A(i,j). $$

# Matrix Equality

Two $m \times n$ matrices, $A$ and $B$, are equal if and only if

$$a_{ij} = b_{ij}$$  

for all  $1 \leq i \leq m$ and $1 \leq j \leq m$

In other words, for two matrices to be equal all elements must be the same

# Matrix Addition

The addition and subtraction of two $m \times n$ matrices, $A$ and $B$, is another $m \times n$ matrix defined by

$$[A \pm B]_{ij} = a_{ij} + b_{ij}$$

For example

$$ \begin{align*}
    \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} +
    \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix} =
    \begin{pmatrix} 1 + 5 & 2 + 6 \\ 3 + 7 & 4 + 8 \end{pmatrix} =
    \begin{pmatrix}6 & 8 \\ 10 & 12 \end{pmatrix}
\end{align*} $$

Matrix addition and substraction is only defined when the two matrices have the same dimension.

# Properties of Matrix Addition

Binary operations can have the following properties

- **Commutative** - changing the order of the operands does not change the results, e.g., $a + b = b + a$

- **Associative** - changing the order of the binary operations in an expression does not change the result, e.g,. $a + (b + c) = (a + b) + c$

- **Distributive** - one binary operation can be distributed over another, e.g., $a(b + c) = ab + ac$

<br>

If $A$, $B$ and $C$ are matrices then matrix addition has the following properties

- $A + B = B + A$ &emsp;(commutative)
- $A + (B + C) = (A + B) + C$ &emsp; (associative)

# Scalar Multiplication

The multiplication of an $m \times n$ matrix $A$ by a scalar $k$ is defined by

$$[kA]_{ij} = ka_{ij}$$

For example

$$ 2 \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} = \begin{pmatrix} 2 & 4 \\ 6 & 8 \end{pmatrix} $$

If $A$ and $B$ are matrices and $k$ and $\ell$ are scalars then scalar multiplication has the following properties

- $kA = Ak$ &emsp; (commutative)
- $k(\ell A) = (k\ell)A = \ell(kA)$ &emsp; (associative)
- $-1 \cdot A = -A$ &emsp; (additive inverse)
- $k(A + B) = kA + kB$ &emsp; (distributive over matrix addition)
- $(k + \ell) A = kA + \ell A$ &emsp; (distributive over scalar addition)

# Matrix Transpose

The **transpose** of an $m \times n$ matrix $A$ is an $n \times m$ matrix denoted by $A^\mathsf{T}$ formed by switching the rows and columns of $A$

$$[A^\mathsf{T}]_{ij} = a_{ji}$$

For example

$$\begin{pmatrix} a & b & c\\ e & f & g \end{pmatrix}^\mathsf{T} = \begin{pmatrix} a & e \\ b & b \\ c & g \end{pmatrix}$$

If $A$ and $B$ are square matrices and $k$ is a scalar then matrix transpose has the following properties

- $(A^\mathsf{T})^\mathsf{T} = A$
- $(A + B)^\mathsf{T} = A^\mathsf{T} + B^\mathsf{T}$
- $(kA)^\mathsf{T}= k(A^\mathsf{T})^\mathsf{T}$
- $(AB)^\mathsf{T} =B^\mathsf{T}A^\mathsf{T}$  &emsp;  ($AB$ is defined in the next few slides)

# Activity

Evaluate the following

\(i) &emsp; $\begin{pmatrix} 2 & 3 & 4 \\ 5 & 6 & 7 \end{pmatrix} + \begin{pmatrix} 1 & 0 & 4 \\ 5 & -2 & 3 \end{pmatrix}$ 

\(ii) &emsp; $\dfrac{1}{2} \begin{pmatrix} 0 & -1 \\ 3 & 2\end{pmatrix}$

\(iii) &emsp; $\begin{pmatrix} 2 & 3 & 5 \end{pmatrix}^\mathsf{T}$

:::{.fragment}
**Solutions** 

\(i) &emsp; $\begin{pmatrix} 2 & 3 & 4 \\ 5 & 6 & 7 \end{pmatrix} + \begin{pmatrix} 1 & 0 & 4 \\ 5 & -2 & 3 \end{pmatrix} = \begin{pmatrix} 3 & 3 & 8 \\ 10 & 4 & 10 \end{pmatrix}$ 

\(ii) &emsp; $\dfrac{1}{2} \begin{pmatrix} 0 & -1 \\ 3 & 2\end{pmatrix} = \begin{pmatrix} 0 & -\frac{1}{2} \\ \frac{3}{2} & 1 \end{pmatrix}$

\(iii) &emsp; $\begin{pmatrix} 2 & 3 & 5 \end{pmatrix}^\mathsf{T} = \begin{pmatrix} 2 \\ 3 \\ 5 \end{pmatrix}$
:::

# Matrix Multiplication

Let $A$ be an $m \times n$ matrix and $B$ be a $p \times q$ matrix then the product $AB$ is defined by

$$[AB]_{ij} = \sum_{j=1}^n a_{ik} b_{kj}$$

$AB$ is only defined is the number of **columns** in $A$ is the same as the number of **rows** in $B$

For example, consider the multiplication of $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$, a useful trick is to write the dimensions of the matrices underneath

$$ \begin{align*}
    AB = \underset{2 \times {\color{red} 2}}{\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}}
    \underset{{\color{red} 2} \times 2}{\begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}}.
\end{align*} $$

If the inner two numbers are the same then $AB$ is defined and the dimensions of $AB$ will be given by the outer two numbers

# Matrix Multiplication Example

Calcualte $AB$ where $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$

$$ \begin{align*}
    \begin{pmatrix}
        {\color{blue}{1}} & {\color{blue}{2}} \\
        {\color{lightgray}{3}} & {\color{lightgray}{4}}
    \end{pmatrix}
    \begin{pmatrix}
        {\color{red}{5}} & {\color{lightgray}{6}} \\
        {\color{red}{7}} & {\color{lightgray}{8}}
    \end{pmatrix} =
    \begin{pmatrix}
        {\color{blue}{1}} ({\color{red}{5}}) + {\color{blue}{2}} ({\color{red}{7}}) & {\color{lightgray}{\square}} \\
        {\color{lightgray}{\square}} & {\color{lightgray}{\square}}
    \end{pmatrix}
    = \begin{pmatrix} 5 + 14 & {\color{lightgray}{\square}} \\ {\color{lightgray}{\square}} & {\color{lightgray}{\square}} \end{pmatrix}
    = \begin{pmatrix} 19 & {\color{lightgray}{\square}} \\ {\color{lightgray}{\square}} & {\color{lightgray}{\square}} \end{pmatrix}
\end{align*} $$

:::{.fragment .fade-up}
$$ \begin{align*}
    \begin{pmatrix}
        {\color{blue}{1}} & {\color{blue}{2}} \\
        {\color{lightgray}{3}} & {\color{lightgray}{4}}
    \end{pmatrix}
    \begin{pmatrix}
        {\color{lightgray}{5}} & {\color{red}{6}} \\
        {\color{lightgray}{7}} & {\color{red}{8}}
    \end{pmatrix} =
    \begin{pmatrix}
        19 & {\color{blue}{1}} ({\color{red}{6}}) + {\color{blue}{2}} ({\color{red}{8}}) \\
        {\color{lightgray}{\square}} & {\color{lightgray}{\square}}
    \end{pmatrix}
    = \begin{pmatrix} 19 & 6 + 16 \\ {\color{lightgray}{\square}} & {\color{lightgray}{\square}} \end{pmatrix}
    = \begin{pmatrix} 19 & 22 \\ {\color{lightgray}{\square}} & {\color{lightgray}{\square}} \end{pmatrix}
\end{align*} $$
:::

:::{.fragment .fade-up}
$$ \begin{align*}
    \begin{pmatrix}
        {\color{lightgray}{1}} & {\color{lightgray}{2}} \\
        {\color{blue}{3}} & {\color{blue}{4}}
    \end{pmatrix}
    \begin{pmatrix}
        {\color{red}{5}} & {\color{lightgray}{6}} \\
        {\color{red}{7}} & {\color{lightgray}{8}}
    \end{pmatrix} =
    \begin{pmatrix}
        19 & 22 \\
        {\color{blue}{3}} ({\color{red}{5}}) + {\color{blue}{4}} ({\color{red}{7}}) & {\color{lightgray}{\square}}
    \end{pmatrix}
    = \begin{pmatrix} 19 & 22 \\ 15 + 28 & {\color{lightgray}{\square}} \end{pmatrix}
    = \begin{pmatrix} 19 & 22 \\ 43 & {\color{lightgray}{\square}} \end{pmatrix}
\end{align*} $$
:::

:::{.fragment .fade-up}
$$ \begin{align*}
    \begin{pmatrix}
        {\color{lightgray}{1}} & {\color{lightgray}{2}} \\
        {\color{blue}{3}} & {\color{blue}{4}}
    \end{pmatrix}
    \begin{pmatrix}
        {\color{lightgray}{5}} & {\color{red}{6}} \\
        {\color{lightgray}{7}} & {\color{red}{8}}
    \end{pmatrix} =
    \begin{pmatrix}
        19 & 22 \\
        43 & {\color{blue}{3}} ({\color{red}{6}}) + {\color{blue}{4}} ({\color{red}{8}})
    \end{pmatrix}
    = \begin{pmatrix} 19 & 22 \\ 43 & 18 + 32 \end{pmatrix}
    = \begin{pmatrix} 19 & 22 \\ 43 & 50 \end{pmatrix}
\end{align*} $$
:::

# Activity

Given the matrices

$$ \begin{align*}
    A &= \begin{pmatrix} 1 & 0 \\ -2 & 3 \end{pmatrix}, &
    B &= \begin{pmatrix} 2 & 3 \\ 1 & 5 \end{pmatrix}, &
    C &= \begin{pmatrix} 1 & 1 & 0 \\ 3 & -2 & 1 \end{pmatrix}, &
    D &= \begin{pmatrix} 1 \\ 3 \end{pmatrix}.
\end{align*} $$

calculate the following (where possible):

\(i) &emsp; $AB$; &emsp;
(ii) &emsp; $BC$; &emsp;
(iii) &emsp; $CD$; &emsp;
(iv) &emsp; $CC^\mathsf{T}$

:::{.fragment}
**Solutions** 

\(i) &emsp; $AB = \begin{pmatrix} 2 & 3 \\ -1 & 9 \end{pmatrix}$

\(ii) &emsp; $BC = \begin{pmatrix}11 & -4 & 3 \\ 16 & -9 & 5 \end{pmatrix}$

\(iii) &emsp; $CD$ is undefined since $C$ has 3 columns and $D$ only has 2 rows

\(iv) &emsp; $CC^\mathsf{T} = \begin{pmatrix} 2 & 1 \\ 1 & 14 \end{pmatrix}$
:::

# Properties of Matrix Multiplication

Matrix multiplication has the following properties

- $AB \neq BA$ &emsp; (matrix multiplication is not commutative)
- $A(BC) = (AB)C$ &emsp; (associative)
- $A(B + C) = AB + AC$ &emsp; (left distributive law)
- $(A + B)C = AC + BC$ &emsp; (right distributive law)
- $(AB)^\mathsf{T} = B^\mathsf{T}A^\mathsf{T}$

# Special Matrices

Some matrices have certain properties which makes them useful for various mathematical applications.

| Name | Explanation | Example |
|:--|:--|:--:|
| Square matrix | An $m \times n$ matrix where $m = n$ | $\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ |
| Zero matrix |  An $m \times n$ matrix of zeros | $\begin{pmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \end{pmatrix}$ | 
| Diagonal matrix | A non-zero square matrix where $a_{ij} = 0$ where $i \neq j$ | $\begin{pmatrix} 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 3 \end{pmatrix}$ |

# Special Matrices cont.

| Name | Explanation | Example |
|:--|:--|:--:|
| Symmetric matrix | A square matrix $A$ such that $a_{ij} = a_{ji}$ | $\begin{pmatrix} 1 & 2 & 3 \\ 2 & 1 & 4 \\ 3 & 4 & 1 \end{pmatrix}$ |
| Upper triangular matrix | A square matrix $A$ such that $a_{ij} = 0$ where $i > j$ | $\begin{pmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{pmatrix}$ |
| Lower triangular matrix | A square matrix $A$ such that $a_{ij} = 0$ where $i < j$ | $\begin{pmatrix} 1 & 0 & 0 \\ 2 & 3 & 0 \\ 4 & 5 & 6 \end{pmatrix}$ |

# Application: The Hill Cipher

The <a href="https://en.wikipedia.org/wiki/Hill_cipher" target="_blank">Hill cipher</a> is a method of encrypting a message that uses matrix multiplication

1. Determine an $n \times n$ encryption matrix
2. Split the message into groups of $n$ characters (use spaces to pad out the last group)
3. Create a code for the message by assigning a number to each character using $A = 1$, $B = 2$, etc. and $\textsf{space} = 0$
4. Convert each group of numbers to a $n \times 1$ matrix
5. Multiply each $n \times 1$ matrix by the encryption matrix
6. Determine the values modulo 26 (the difference from the closest multiple of 26 that is less than the value)
7. Convert the numbers back into characters, this is the decrypted message
   
To decrypt the message repeat these steps except we multipy the message matrix by the inverse of the encryption matrix

# Example: Hill Cipher Encryption

Encrypt the message `ATTACK AT ONCE` using the encryption matrix $\begin{pmatrix} 1 & 2 \\ 1 & 3 \end{pmatrix}$

:::{.fragment}
- Split the message into groups of 2 characters: `AT TA CK -A T- ON CE`
:::

:::{.fragment}
- The message code is $\begin{pmatrix} 1 \\ 20 \end{pmatrix}$
  $\begin{pmatrix} 20 \\ 1 \end{pmatrix}$
  $\begin{pmatrix} 3 \\ 11 \end{pmatrix}$
  $\begin{pmatrix} 0 \\ 1 \end{pmatrix}$
  $\begin{pmatrix} 20 \\ 0 \end{pmatrix}$
  $\begin{pmatrix} 15 \\ 14 \end{pmatrix}$
  $\begin{pmatrix} 3 \\ 5 \end{pmatrix}$
:::

:::{.fragment}
- Multiply each matrix by the encryption matrix and determine modulo 26, e.g.,

$$ \begin{align*}
    \begin{pmatrix} 1 & 2 \\ 1 & 3 \end{pmatrix}
    \begin{pmatrix} 1 \\ 20 \end{pmatrix}
    &= 
    \begin{pmatrix} 41 \\ 61 \end{pmatrix}
    \equiv
    \begin{pmatrix} 15 \\ 9 \end{pmatrix} \quad (\operatorname{mod} 26)
\end{align*} $$

- The encrypted code is 
  $\begin{pmatrix} 15 \\ 9 \end{pmatrix}$
  $\begin{pmatrix} 22 \\ 23 \end{pmatrix}$
  $\begin{pmatrix} 25 \\ 10 \end{pmatrix}$
  $\begin{pmatrix} 2 \\ 3 \end{pmatrix}$
  $\begin{pmatrix} 20 \\ 20 \end{pmatrix}$ 
  $\begin{pmatrix} 17 \\ 5 \end{pmatrix}$
  $\begin{pmatrix} 13 \\ 18 \end{pmatrix}$
:::

:::{.fragment}
- The encrypted message is `OIVWYJBCTTQEMR`
:::

<!-- | A  | B  | C  | D  | E  | F  | G  | H  | I  | J  | K  | L  | M  |
     | 1  | 2  | 3  | 4  | 5  | 6  | 7  | 8  | 9  | 10 | 11 | 12 | 13 |
     | N  | O  | P  | Q  | R  | S  | T  | U  | V  | W  | X  | Y  | Z  | Space | 
     | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 0 | -->

# Example: Hill Cipher Decryption

Decrypt the message `OIVWYJBCTTQEMR` using the decryption matrix $\begin{pmatrix} 3 & -2 \\ -1 & 1 \end{pmatrix}$

:::{.fragment}
- Split the message into groups of 2 characters: `OI VW YJ BC TT QE MR`
:::

:::{.fragment}
- The coded message is 
  $\begin{pmatrix} 15 \\ 9 \end{pmatrix}$
  $\begin{pmatrix} 22 \\ 23 \end{pmatrix}$
  $\begin{pmatrix} 25 \\ 10 \end{pmatrix}$
  $\begin{pmatrix} 2 \\ 3 \end{pmatrix}$
  $\begin{pmatrix} 20 \\ 20 \end{pmatrix}$
  $\begin{pmatrix} 17 \\ 5 \end{pmatrix}$
  $\begin{pmatrix} 13 \\ 18 \end{pmatrix}$
:::

:::{.fragment}

- Multiply by the decryption matrix and determine modulo 26, e.g.,

$$ \begin{align*}
    \begin{pmatrix}
        3 & -2 \\ 
        -1 & 1
    \end{pmatrix} 
    \begin{pmatrix} 15 \\ 9 \end{pmatrix}
    =
    \begin{pmatrix} 27 \\ -6 \end{pmatrix}
    \equiv
    \begin{pmatrix} 1 \\ 20 \end{pmatrix} \quad (\operatorname{mod} 26)
\end{align*} $$

- The decrypted code is 
  $\begin{pmatrix} 1 \\ 20 \end{pmatrix}$
  $\begin{pmatrix} 20 \\ 1 \end{pmatrix}$
  $\begin{pmatrix} 3 \\ 11 \end{pmatrix}$
  $\begin{pmatrix} 0 \\ 1 \end{pmatrix}$
  $\begin{pmatrix} 20 \\ 0 \end{pmatrix}$
  $\begin{pmatrix} 15 \\ 14 \end{pmatrix}$
  $\begin{pmatrix} 3 \\ 5 \end{pmatrix}$
:::

:::{.fragment}
- The decrypted message is `ATTACK AT ONCE`
:::