---
title: "Systems of Linear Equations I"
subtitle: Linear Algebra and Programming Skills
author: "Dr Jon Shiach"
format:
  revealjs:
    slide-level: 3
    transition: slide
    navigation-mode: vertical
    theme: [default, custom.scss]
    controls-layout: bottom-right
    controls-tutorial: true
    smaller: true
    presentation-h2-font-size: 0.5em
---

# Systems of Linear Equations

A **system of linear equations** is a collection of one or more linear equations expressed using the same set of variables

$$ \begin{align*}
    a_{11} x_1+a_{12} x_2+\cdots +a_{1n}x_n &=b_1, \\
    a_{21} x_1+a_{22} x_2+\cdots+a_{2n}x_n &=b_2, \\
    &\vdots \\
    a_{m1} x_1+a_{m2} x_2+\cdots+a_{mn}x_n &=b_m,
\end{align*} $$

where 

- $x_1, x_2, \ldots, x_n$ are **variables**, 
- $a_{11}, a_{12}, \ldots a_{mn}$ are **coefficients**
- $b_1, b_2, \ldots, b_n$ are **constants**.

The solution to the system are the values of $x_i$ that satsify **all** equations in the system.

# Representing systems of linear equation as a matrix equation

Systems of linear equations are often represented using the matrix equation 

$$A \mathbf{x} = \mathbf{b}$$

where

- $A$ is a $m \times n$ **coefficient matrix** containing the values of $a_{ij}$
- $\mathbf{x}$ is a $m \times$ matrix called the **variable vector** containing the variables $x_i$ 
- $\mathbf{b}$ is a $m \times 1$ matrix called the **constant vector** containing the constant terms $b_i$.

$$\begin{pmatrix}
        a_{11} & a_{12} & \cdots & a_{1n} \\
        a_{21} & a_{22} & \cdots & a_{2n} \\
        \vdots & \vdots & \ddots & \vdots \\
        a_{m1} & a_{m2} & \cdots & a_{mn}
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix}
    =
    \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_m \end{pmatrix}$$

---

For example, the follow system of linear equations

$$ \begin{align*}
    2x_1 + x_2 &= 4, \\
    4x_1 + 3x_2 &= 10.
\end{align*} $$

can be written as the matrix equation

$$ \begin{align*}
    \begin{pmatrix}
        2 & 1 \\
        4 & 3
    \end{pmatrix}
    \begin{pmatrix}
        x_1 \\ x_2
    \end{pmatrix} =
    \begin{pmatrix}
        4 \\ 10
    \end{pmatrix}.
\end{align*} $$

# Solving Systems using the Inverse Matrix

Given the system of linear equations $A \mathbf{x} = \mathbf{b}$ then solving for $\mathbf{x}$

$$ \begin{align*}
    A\mathbf{x} &= \mathbf{b}\\
    A^{-1}A \mathbf{x} &= A^{-1}\mathbf{b}\\
    \mathbf{x} &= A^{-1}\mathbf{b} \qquad (\text{since } I = A^{-1}A).
\end{align*} $$

So we can use the inverse of the coefficient matrix $A$ to solve for $\mathbf{x}$.

For example, consider the following system of linear equations

$$ \begin{pmatrix}
    2 & 1 \\
    4 & 3
\end{pmatrix}
\begin{pmatrix}
    x_1 \\ x_2
\end{pmatrix} =
\begin{pmatrix}
    4 \\ 10
\end{pmatrix}. $$

The coefficient matrix and constant vector are

$$ \begin{align*}
    A &= \begin{pmatrix}
        2 & 1 \\
        4 & 3
    \end{pmatrix}, &
    \mathbf{b} &= \begin{pmatrix} 4 \\ 10 \end{pmatrix},
\end{align*} $$

---

$$ \begin{align*}
    A &= \begin{pmatrix}
        2 & 1 \\
        4 & 3
    \end{pmatrix}, &
    \mathbf{b} &= \begin{pmatrix} 4 \\ 10 \end{pmatrix},
\end{align*} $$

The inverse of the coefficient matrix is

$$ A^{-1} = \begin{pmatrix}
    2 & 1 \\
    4 & 3
\end{pmatrix}^{-1}
= \frac{1}{2} \begin{pmatrix}
    3 & -1 \\
    -4 & 2
\end{pmatrix}. $$

Using $\mathbf{x} = A^{-1}\mathbf{b}$ the solution is

$$ \mathbf{x} = \frac{1}{2}
\begin{pmatrix}
    3 & -1 \\
    -4 & 2
\end{pmatrix}
    \begin{pmatrix} 4 \\ 10 \end{pmatrix} =
    \begin{pmatrix} 1 \\ 2 \end{pmatrix}.$$

Checking the solution

$$ \begin{pmatrix}
    2 & 1 \\
    4 & 3
\end{pmatrix}
\begin{pmatrix}
    1 \\ 2
\end{pmatrix} =
\begin{pmatrix}
    4 \\ 10
\end{pmatrix} = \mathbf{b}. \qquad \checkmark $$

# Activity

Solve the following systems of linear equations using the inverse of the coefficient matrix:

\(i) &emsp; $\begin{array}{rl}
        x_1 - 2x_2  \!\!\!\! &= 11, \\
        2x_1 + 4x_2  \!\!\!\! &= -18.
    \end{array}$; &emsp;
\(ii) &emsp; $\begin{array}{rl}
        x_1 - 2x_2 + 3x_3 \!\!\!\! &= -7, \\
        2x_2 - 4x_3  \!\!\!\! &= 8, \\
        3x_1 + x_2 - 4x_3  \!\!\!\! &= 7.
    \end{array}$

:::{.fragment}
**Solution**

\(i) &emsp; $\mathbf{x} = \begin{pmatrix} 1 \\ -5 \end{pmatrix}$

\(ii) &emsp; $\mathbf{x} = \begin{pmatrix} 1 \\4 \\ 0 \end{pmatrix}$
:::

# Cramer's Rule

**Cramer's rule** is an explicit rule for calculating the solution to a system of linear equations of the form $A\mathbf{x}=\mathbf{b}$ 

$$ x_i = \frac{\det(A_i)}{\det(A)}, $$

where $A_i$ is a matrix obtained by replacing column $i$ of $A$ with $\mathbf{b}$.

---

For example, consider the solution to the system 

$$ \begin{align*}
    A &= \begin{pmatrix}
        2 & 1 \\
        4 & 3
    \end{pmatrix}, &
    \mathbf{b} &= \begin{pmatrix} {\color{red} 4} \\ {\color{red}{10}} \end{pmatrix},
\end{align*} $$

Using Cramer's rule

$$ \begin{align*}
    x_1 &= \frac{\det\begin{pmatrix} {\color{red} 4} & 1 \\ {\color{red}{10}} & 3 \end{pmatrix}}{\det \begin{pmatrix} 2 & 1 \\ 4 & 3 \end{pmatrix}} = \frac{2}{2} = 1, \\
    x_2 &= \frac{\det\begin{pmatrix} 2 & {\color{red} 4} \\ 4 & {\color{red}{10}} \end{pmatrix}}{2} = \frac{4}{2} = 2. 
\end{align*} $$

# Cramer's Rule Activity

Solve the following systems of linear equations using Cramer's rule

\(i) &emsp; $\begin{array}{rl}
    3x_1 - 2x_2  \!\!\!\! &= -4, \\
    x_1 - 3x_2  \!\!\!\! &= 1.
\end{array}$; &emsp;
\(ii) &emsp; $\begin{array}{rl}
    -2x_1 - 3x_2 - x_3 \!\!\!\!  &= -5, \\
    -4x_1 + 4x_2 + 3x_3  \!\!\!\! &= -20, \\
    -3x_1  \!\!\!\! &= -12.
\end{array}$

:::{.fragment}
**Solution**

\(i) &emsp; $\mathbf{x} = \begin{pmatrix} -2 \\ -1 \end{pmatrix}$

\(ii) &emsp; $\mathbf{x} = \begin{pmatrix} 4 \\ -1 \\ 0 \end{pmatrix}$
:::