---
title: "Systems of Linear Equations II"
subtitle: Linear Algebra and Programming Skills
author: "Dr Jon Shiach"
format:
  revealjs:
    slide-level: 3
    transition: slide
    navigation-mode: vertical
    theme: [default, custom.scss]
    controls-layout: bottom-right
    controls-tutorial: true
    smaller: true
    presentation-h2-font-size: 0.5em
---

# Systems of Linear Equations (recap)

A **system of linear equations** is a collection of one or more linear equations expressed using the same set of variables

$$ \begin{align*}
    a_{11} x_1+a_{12} x_2+\cdots +a_{1n}x_n &=b_1, \\
    a_{21} x_1+a_{22} x_2+\cdots+a_{2n}x_n &=b_2, \\
    &\vdots \\
    a_{m1} x_1+a_{m2} x_2+\cdots+a_{mn}x_n &=b_m,
\end{align*} $$

We can write this as the matrix equation $A\mathbf{x} = \mathbf{b}$

$$ \begin{align*}
    \begin{pmatrix}
        a_{11} & a_{12} & \cdots & a_{1n} \\
        a_{21} & a_{22} & \cdots & a_{2n} \\
        \vdots & \vdots & \ddots & \vdots \\
        a_{m1} & a_{m2} & \cdots & a_{mn}
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix}
    =
    \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_m \end{pmatrix}
\end{align*} $$

# Augmented Matrix

The **augmented matrix** is a representation of a system of linear equations $A\mathbf{x}=\mathbf{b}$ such $A$ and $\mathbf{b}$ are combined into a single matrix $(A \mid \mathbf{b})$.

$$ \left(
\begin{array}{cccc|c}
    a_{11} & a_{12} & \cdots & a_{1n} & b_1 \\
    a_{21} & a_{22} & \cdots & a_{2n} & b_2 \\
    \vdots & \vdots & \ddots & \vdots & \vdots \\
    a_{m1} & a_{m2} & \cdots & a_{mn} & b_n
\end{array}
\right). $$

---

For example, express the following system of linear equations as an augmented matrix

$$ \begin{align*}
    3x_1 + x_2 - 2x_3 &= 1, \\
    x_1 - x_2 + 2x_3 &= 3, \\
    2x_1 - 3x_2 + 7x_3 &= 4.
\end{align*} $$

:::{.fragment}
**Solution**

$$ \left( \begin{array}{ccc|c}
        3 & 1 & -2 & 1 \\
        1 & -1 & 2 & 3 \\
        2 & -3 & 7 & 4
    \end{array} \right). $$
:::

# Row Echelon Form (REF)

A matrix is said to be in **Row Echelon Form (REF)** if the following conditions are satisfied:

- Any non-zero rows are above any all-zero rows
- In each non-zero row the **pivot element**, the first non-zero element in the row, is to the right of the pivot element in the row above

For example, the following matrices are in row echelon form and the red numbers are the pivot elements

$$ \begin{align*}
    &\begin{pmatrix} \color{red}{1} & 2 \\ 0 & \color{red}{3} \end{pmatrix}, &
    &\begin{pmatrix} \color{red}{1} & 2 & 3 \\ 0 & 0 & \color{red}{4} \end{pmatrix}, &
    &\begin{pmatrix} 0 & \color{red}{1} & 3\\ 0 & 0 & \color{red}{4} \\ 0 & 0 & 0\end{pmatrix}.
\end{align*} $$

Note that the elements below the pivot elements are all zero.

**Row reduction** is the process of applying elementary row operations to a matrix to reduce it to row echelon form

# Elementary Row Operations (ERO)

The three **elementary row operations** that can be applied to a linear system of equations without changing the solution are

- Type I: swap any two rows of the system
- Type II: multiply one row by a non-zero scalar
- Type III: replace a single row by itself plus a multiple of another row

# Row Reduction Example

Row reduce the augmented matrix from the previous example to row echelon form

$$ \left( \begin{array}{ccc|c}
        3 & 1 & -2 & 1 \\
        1 & -1 & 2 & 3 \\
        2 & -3 & 7 & 4
    \end{array} \right). $$

:::{.fragment}
**Solution**

Subtract row 1 multiplied by $\dfrac{1}{3}$ from row 2.

$$ \begin{align*}
  \left( \begin{array}{ccc|c}
      \color{red}{ 3} & 1 & -2 & 1 \\
      \color{blue}{ 1 - \frac{1}{3}(3)} & -1 - \frac{1}{3}(1) & 2 - \frac{1}{3}(-2) & 3 - \frac{1}{3}(1) \\
      \color{blue}{ 2} & -3 & 7 & 4
  \end{array} \right) &
  \longrightarrow
  \left( \begin{array}{ccc|c}
      \color{red}{ 3} & 1 & -2 & 1 \\
      \color{blue}{ 0} & -\frac{4}{3} & \frac{8}{3} & \frac{8}{3} \\
      \color{blue}{ 2} & -3 & 7 & 4
  \end{array} \right).
\end{align*} $$
:::

:::{.fragment}
Subtract row 1 multiplied by $\dfrac{2}{3}$ from row 3.
:::

---

$$ \left( \begin{array}{ccc|c}
    \color{red}{3} & 1 & -2 & 1 \\
    \color{blue}{0} & -\frac{4}{3} & \frac{8}{3} & \frac{8}{3} \\
    \color{blue}{2 - \frac{2}{3}(3)} & -3 - \frac{2}{3}(1) & 7 - \frac{2}{3}(-2) & 4 - \frac{2}{3}(1)
\end{array} \right)
\longrightarrow  
\left( \begin{array}{ccc|c}
    \color{red}{3} & 1 & -2 & 1 \\
    \color{blue}{0} & -\frac{4}{3} & \frac{8}{3} & \frac{8}{3} \\
    \color{blue}{0} & -\frac{11}{3} & \frac{25}{3} & \frac{10}{3}
\end{array} \right). $$

:::{.fragment}
Subtract row 2 multiplied by $-\dfrac{11}{3} \div \left(-\dfrac{4}{3}\right) = \dfrac{11}{4}$ from row 3.

$$ \left( \begin{array}{ccc|c}
    3 & 1 & -2 & 1 \\
    0 & \color{red}{-\frac{4}{3}} & \frac{8}{3} & \frac{8}{3} \\
    0 & \color{blue}{-\frac{11}{3} - \frac{11}{4}(-\frac{4}{3})} & \frac{25}{3} - \frac{11}{4}(\frac{8}{3}) & \frac{10}{3} - \frac{11}{4}(\frac{8}{3})
\end{array} \right)
\longrightarrow
\left( \begin{array}{ccc|c}
    3 & 1 & -2 & 1 \\
    0 & \color{red}{-\frac{4}{3}} & \frac{8}{3} & \frac{8}{3} \\
    0 & \color{blue}{0} & 1 & -4
\end{array} \right). $$

Now the augmented matrix is in row echelon form.
:::

# Back Substitution

The row echelon form of the augmented matrix from the previous example is

$$ \left( \begin{array}{ccc|c}
    3 & 1 & -2 & 1 \\
    0 & \color{red}{-\frac{4}{3}} & \frac{8}{3} & \frac{8}{3} \\
    0 & \color{blue}{0} & 1 & -4
\end{array} \right)$$

Writing this as a system of equations we have

$$ \begin{align*}
    3x_1 + x_2 - 2x_3 &= 1, \\
    -\frac{4}{3}x_2 + \frac{8}{3} x_3 &= \frac{8}{3}, \\
    x_3 &= -4
\end{align*} $$

We know from the last equation that $x_3 = -4$, substitute this into the second equation 

---

$$ \begin{align*}
    -\frac{4}{3} x_2 + \frac{8}{3}(-4) &= \frac{8}{3} \\
    \therefore x_2 &= -\frac{3}{4}\left(\frac{8}{3} + \frac{32}{3} \right) = -10
\end{align*} $$

Substituting $x_2 = 3$ and $x_3 = -4$ into the first equation 

$$ \begin{align*}
    3x_1 - 10 - 2(-4) &= 1 \\
    \therefore x_1 &= \frac{1}{3}(1 + 10 - 8) = 1
\end{align*} $$

This process of going solving $x_i$ going backwards through the system is known as **back substitution**

# Gaussian Elimination

**Gaussian elimination** solves a system of linear equations by reducing the augmented matrix to row echelon form and then solving using back substitution

- Form the augmented matrix $( A \mid \mathbf{b} )$
- Set pivot row $k$ to 1
- For each column $j$ from 1 to $n$:
    - If the pivot element $a_{kj} = 0$
        - Identify a row $i$ where $i > j$ and $a_{ij} \neq 0$, if no such row exists skip to the next column
        - Swap row $i$ with row $k$
    - For each row $i$ from $k+1$ to $m$:
        - Subtract $\dfrac{a_{ij}}{a_{jj}}$ times row $j$ from row $i$
- Solve for $\mathbf{x}$ using back substitution

# Activity

Solve the following systems of linear equations using Gaussian elimination

\(i) &emsp; $\begin{align*}
    x_1 + 2x_2 &= 7, \\
    3x_1 - 4x_2 &= 1.
    \end{align*}$; &emsp;
\(ii) &emsp; $\begin{align*}
    x_1 + x_3 &= 3, \\
    -2x_1 + x_2 + 3x_3 &= 3, \\
    -x_1 + 2x_2 + 4x_3 &= 5.
\end{align*}$

:::{.fragment}
**Solution**

\(i) &emsp; $x_1 = 3$, $x_2 = 2$

\(ii) &emsp; $x_1 = 1$, $x_2 = -1$, $x_3 = 2$
:::

# Partial Pivoting

Consider the following linear system of equations

$$ \begin{pmatrix}0.001 & 1 \\ 1 & 1 \end{pmatrix}
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix} =
\begin{pmatrix}1 \\ 2 \end{pmatrix}. $$

Using Gaussian elimination to solve this system

$$ \begin{align*}
    &\left( \begin{array}{cc|c}
        0.001 & 1 & 1 \\
        1 & 1 & 2
    \end{array} \right)
    \begin{array}{l} \\  R_2 - 1000R_1 \end{array} 
    \longrightarrow 
    \left( \begin{array}{cc|c}
        0.001 & 1 & 1 \\
        0 & -999 & -998
    \end{array} \right)
    \begin{array}{l} \\  -\dfrac{1}{999}R_2 \end{array} \\ \\
    \longrightarrow &
    \left( \begin{array}{cc|c}
        0.01 & 1 & 1 \\
        0 & 1 & 0.999\ldots
    \end{array} \right).
\end{align*} $$

So $x_2 = 0.999\ldots\approx 1$ and $x_1 = \dfrac{1 - 1(1)}{0.001} = 0$

---

Substitute $x_1 = 0$ and $x_2 = 1$ into the original system

$$ \begin{align*}
    0.01(0) + 1(1) &= 1, \\
    1(0) + 1(1) &= 1 \neq 2.
\end{align*} $$

So the solution is clearly wrong. Lets solve the system again but perform a row swap before eliminating the value beneath the pivot

$$ \begin{align*}
    & \left(\begin{array}{cc|c}
        0.001 & 1 & 1 \\
        1 & 1 & 2
    \end{array} \right)
    \begin{array}{l} R_1 \leftrightarrow R_2  \\ \phantom{x} \end{array}&
    \longrightarrow &
    \left( \begin{array}{cc|c}
        1 & 1 & 2 \\
        0.001 & 1 & 1
    \end{array} \right)
    \begin{array}{l} \\  R_2 - 0.001 R_1 \end{array} \\ \\
    \longrightarrow &
    \left( \begin{array}{cc|c}
        1 & 1 & 2 \\
        0 & 0.999 & 0.998
    \end{array} \right)
\end{align*} $$

Backsubtitution gives $x_2 = 0.999\ldots \approx 1$ and $x_1 = 1$

$$ \begin{align*}
    0.01(1) + 1(1) &= 1.01 \approx 1, \\
    1(1) + 1(1) &= 2.
\end{align*} $$

---

So performing the row swap gave us a much more accurate solution

The reason for this is that it ensured the value of the pivot is larger than the element below, so when applying the ERO

$$ R_i - \frac{a_{ij}}{a_{jj}} R_j \qquad i = j+1, \ldots, n$$

where $j$ is the pivot row we have $\dfrac{a_{ij}}{a_{jj}} \leq 1$

This is known as **partial pivoting** and is used to improve the accuracy of Gaussian elimination
 
# Gaussian Elimination with Partial Pivoting

- Form the augmented matrix $( A \mid \mathbf{b} )$
- Set pivot row $k$ to 1
- For each column $j$ from 1 to $n$:
    - Identify the row $i$ where $i \geq k$ with the largest absolute value in column $j$
    - If the largest absolute value is zero skip to next column
    - Swap row $i$ with row $k$.
    - For each row $i$ from $k+1$ to $m$:
        - Subtract $\dfrac{a_{ij}}{a_{jj}}$ times row $j$ from row $i$
- Solve for $\mathbf{x}$ using back substitution

# Activity 

Solve the system of linear equations using Gaussian elimination with partial pivoting.

$$ \begin{align*}
   x_1 - x_2 + 3x_3 &= 13, \\
   4x_1 - 2x_2 + x_3 &= 15, \\
   -3x_1 - x_2 + 4x_3 &= 8.
\end{align*} $$

:::{.fragment}
**Solution**

$x_1 = 2$, $x_2 = -2$, $x_3 = 3$
:::