---
title: "Systems of Linear Equations II"
subtitle: Linear Algebra and Programming Skills
author: "Dr Jon Shiach"
format:
  revealjs:
    slide-level: 3
    transition: slide
    navigation-mode: vertical
    theme: [default, custom.scss]
    controls-layout: bottom-right
    controls-tutorial: true
    smaller: true
    presentation-h2-font-size: 0.5em
---

# Gaussian Elimination (recap)

- Gaussian elimination uses Elementary Row Operations (ERO) to reduce a system of linear equations to row echelon form

- The solution to the system is then found using backsubsitution

- Partial pivoting reduces the errors due to rounding using row swaps to ensure the pivot has a higher absolute value then the elements beneath it

# Example

Solve the following system of equations using partial pivotting

$$ \begin{align*}
    3x_1 + x_2 - 2x_3 &= 1, \\
    x_1 - x_2 + 2x_3 &= 3, \\
    2x_1 - 3x_2 + 7x_3 &= 4.
\end{align*} $$

$$ \begin{align*}
    & \left( \begin{array}{ccc|c}
        3 & 1 & -2 & 1 \\
        1 & -1 & 2 & 3 \\
        2 & -3 & 7 & 4
    \end{array} \right)
    \begin{matrix} \\ R_2 - \frac{1}{3}R_1 \\ R_3 - \frac{2}{3} R_1 \end{matrix} 
    \longrightarrow
    \left( \begin{array}{ccc|c}
        3 & 1 & -2 & 1 \\
        0 & -\frac{4}{3} & \frac{8}{3} & \frac{8}{3} \\
        0 & -\frac{11}{3} & \frac{25}{3} & \frac{10}{3}
    \end{array} \right)
    \begin{matrix} \\ R_2 \leftrightarrow R_1 \\ \phantom{\frac{x}{x}} \end{matrix} \\
    \longrightarrow &
    \left( \begin{array}{ccc|c}
        3 & 1 & -2 & 1 \\
        0 & -\frac{11}{3} & \frac{25}{3} & \frac{10}{3} \\
        0 & -\frac{4}{3} & \frac{8}{3} & \frac{8}{3}
    \end{array} \right)
    \begin{matrix} \\ \\ R_3 - \frac{4}{11}R_2 \end{matrix} 
    \longrightarrow
    \left( \begin{array}{ccc|c}
        3 & 1 & -2 & 1 \\
        0 & -\frac{11}{3} & \frac{25}{3} & \frac{10}{3} \\
        0 & 0 & -\frac{4}{11} & \frac{16}{11}
    \end{array} \right)
\end{align*} $$

---

$$ \left( \begin{array}{ccc|c}
        3 & 1 & -2 & 1 \\
        0 & -\frac{11}{3} & \frac{25}{3} & \frac{10}{3} \\
        0 & 0 & -\frac{4}{11} & \frac{16}{11}
    \end{array} \right) $$

Solving by back substitution

$$ \begin{align*}
    -\frac{4}{11} x_3 &= \frac{16}{11} 
    & \therefore x_3 &= -\frac{11}{4} \left(\frac{16}{11} \right) = -4, \\ \\
    -\frac{11}{3} x_2 + \frac{25}{3} (-4) &= \frac{10}{3}
    & \therefore x_2 &= -\frac{3}{11} \left( \frac{10}{3} + \frac{100}{3} \right) = -10, \\ \\
    3x_1 - 10 - 2(-4) &= 1
    & \therefore x_1 &= \frac{1}{3}(1 + 10 - 8) = 1
\end{align*} $$

# Reduced Row Echelon Form

A matrix is said to be in **Reduced Row Echelon Form (RREF)** if it satisfies the following conditions:

- It is in row echelon form
- The leading entry in each non-zero row has a value of 1
- The leading entry in each non-zero row is the only non-zero element in its column

For example the following matrices are in reduced row echelon form:

$$ \begin{align*}
    &\begin{pmatrix}
        {\color{red}{1}} & 0 \\
        0 & {\color{red}{1}}
    \end{pmatrix}, &
    &\begin{pmatrix}
        {\color{red}{1}} & 2 & 0 \\
        0 & 0 & {\color{red}{1}}
    \end{pmatrix}, &
    &\begin{pmatrix}
        {\color{red}{1}} & 0 & 2 & 0 \\
        0 & {\color{red}{1}} & 3 & 0 \\
        0 & 0 & 0 & {\color{red}{1}}
    \end{pmatrix}
\end{align*} $$

# Gauss-Jordan Elimination

Gauss-Elimination solves a system of linear equations by row reducing the augmented matrix to reduced row echelon form

- Form the augmented matrix $( A \mid \mathbf{b} )$
- Set pivot row $k$ to 1
- For each column $j$ from 1 to $n$:
    - Perform row swap of the pivot row if necessary
    - If pivot element is zero and all elements beneath the pivot element are zero skip to the next column
    - For each row $i$ from $1$ to $m$ where $i \neq k$:
        - Subtract $\dfrac{a_{ij}}{a_{jj}}$ times row $j$ from row $i$
    - Divide row $k$ by pivot $a_{kj}$

# Example

Use Gauss-Jordan elimination without partial pivoting to solve the following system of linear equations

$$ \begin{align*}
    4x_1 + 3x_2 + 2x_3 &= 9 \\
    5x_1 + x_2 + 5x_3 &= 8, \\
    5x_1 + x_2 + 2x_3 &= 2
\end{align*} $$

:::{.fragment}
**Solution**

$$ \begin{align*}
    & \left( \begin{array}{ccc|c}
        4 & 3 & 2 & 9 \\
        5 & 1 & 5 & 8 \\
        5 & 1 & 2 & 2
    \end{array} \right)
    \begin{matrix} \frac{1}{4}R_1 \\ \phantom{x} \\ \phantom{x} \end{matrix}
    \qquad \qquad \longrightarrow
    \left( \begin{array}{ccc|c}
        1 & \frac{3}{4} & \frac{1}{2} & \frac{9}{2} \\
        5 & 1 & 5 & 8 \\
        5 & 1 & 2 & 2
    \end{array} \right)
    \begin{matrix} \\ R_2 - 5R_1 \\ R_3 - 5R_1 \end{matrix} \\
    \longrightarrow &
    \left( \begin{array}{ccc|c}
        1 & \frac{3}{4} & \frac{1}{2} & \frac{9}{2} \\
        0 & -\frac{11}{4} & \frac{5}{2} & -\frac{13}{4} \\
        0 & -\frac{11}{4} & -\frac{1}{2} & -\frac{37}{4}
    \end{array} \right)
    \begin{matrix} \\ -\frac{4}{11} R_2 \\ \phantom{-\frac{4}{11}} \end{matrix} 
    \longrightarrow
    \left( \begin{array}{ccc|c}
        1 & \frac{3}{4} & \frac{1}{2} & \frac{9}{2} \\
        0 & 1 & -\frac{10}{11} & \frac{13}{11} \\
        0 & -\frac{11}{4} & -\frac{1}{2} & -\frac{37}{4}
    \end{array} \right)
    \begin{matrix} R_1 - \frac{3}{4} R_2 \\ 0 \\ R_3 + \frac{11}{4}R_2 \end{matrix} \\
\end{align*} $$
:::

---

$$ \begin{align*}
    \longrightarrow &
    \left( \begin{array}{ccc|c}
        1 & 0 & \frac{13}{11} & \frac{15}{11} \\
        0 & 1 & -\frac{10}{11} & \frac{13}{11} \\
        0 & 0 & -3 & -6
    \end{array} \right)
    \begin{matrix} \\ \\ -\frac{1}{3}R_3 \end{matrix} 
    \longrightarrow 
    \left( \begin{array}{ccc|c}
        1 & 0 & \frac{13}{11} & \frac{15}{11} \\
        0 & 1 & -\frac{10}{11} & \frac{13}{11} \\
        0 & 0 & 1 & 2
    \end{array} \right)
    \begin{matrix} R_1 - \frac{13}{11} R_3 \\ R_2 + \frac{10}{11} R_3 \\ \phantom{x} \end{matrix} \\
    \longrightarrow &
    \left( \begin{array}{ccc|c}
        1 & 0 & 0 & -1 \\
        0 & 1 & 0 & 3 \\
        0 & 0 & 1 & 2
    \end{array} \right)
\end{align*} $$

Writing this as a system of equations

$$ \begin{align*}
    x_1 &= -1, \\
    x_2 &= 3, \\
    x_£ &= 2,
\end{align*} $$

so there's no need to perform back substitution

# Activity

Solve the following system of equations using Gaussian elimination

$$ \begin{align*}
    2x_2 + x_3 &= -1, \\
    3x_1 + 3x_2 + x_3 &= 8, \\
    -x_1 + 3x_2 + 2x_3 &= -4.
\end{align*} $$

:::{.fragment}
**Solution**

$x_1 = 3$, $x_2 = -1$, $x_3 = 1$
:::

# Elementary Matrices

An **elementary matrix** is an $n \times n$ square matrix obtained by performing a single elementary row operation to the identity matrix $I_n$

| Row operation | Elementary Matrix |
|:--:|:--:|
| $R_1 \leftrightarrow R_2$ | $\begin{pmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{pmatrix}$ |
| $kR_2$ | $\begin{pmatrix} 1 & 0 & 0 \\ 0 & k & 0 \\ 0 & 0 & 1 \end{pmatrix}$ |
| $R_3 + kR_1$ | $\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ k & 0 & 1 \end{pmatrix}$ |

---

If $A$ is an $n \times n$ matrix and $E$ is an elementary matrix the product $EA$ is equivalent to performing the elementary row operation used to obtain $E$ on $A$.

For example, if $A = \begin{pmatrix} 1 & 0 & 4 \\ 2 & -1 & 3 \\ 0 & 5 & 1 \end{pmatrix}$ 

- $R_1 \leftrightarrow R_2$: &emsp;  $EA = \begin{pmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} 1 & 0 & 4 \\ 2 & -1 & 3 \\ 0 & 5 & 1 \end{pmatrix} =  \begin{pmatrix} 2 & -1 & 3 \\ 1 & 0 & 4 \\ 0 & 5 & 1 \end{pmatrix}$
  
- $-2R_2$ &emsp; &emsp; &emsp; $EA = \begin{pmatrix} 1 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} 1 & 0 & 4 \\ 2 & -1 & 3 \\ 0 & 5 & 1 \end{pmatrix}=\begin{pmatrix} 1 & 0 & 4 \\ -4 & 2 & -6 \\ 0 & 5 & 1 \end{pmatrix}$

- $R_3 + 3R_2$ &emsp;  $EA = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 3 & 1 \end{pmatrix} \begin{pmatrix} 1 & 0 & 4 \\ 2 & -1 & 3 \\ 0 & 5 & 1 \end{pmatrix} = \begin{pmatrix} 1 & 0 & 4 \\ 2 & -1 & 3 \\ 6 & 2 & 10 \end{pmatrix}$

# Calculating Matrix Inverse using Gauss-Jordan Elimination

If we apply $k$ elementary row operations with corresponding elementary matrices $E_1, E_2, \ldots, E_k$ to row reduce $A$ to reduced row echelon form then

$$ I = E_k E_{k-1} \cdots E_2 E_1 A$$

Multiplying $A^{-1}$ to the right of both sides gives

$$ \begin{align*}
I A^{-1} &= E_k E_{k-1} \cdots E_2 E_1 A A^{-1} \\
A^{-1} &= E_k E_{k-1} \cdots E_2 E_1 I
\end{align*} $$

So if we use the same row operations to reduce a matrix $A$ to RREF to the identity matrix, then the resulting matrix is $A^{-1}$

So we apply Gauss-Jordan elimination to the augmented matrix $(A \mid I)$ and the matrix to the right of the partition is $A^{-1}$

# Inverse using GJE Example

Calculate the inverse of the matrix $A = \begin{pmatrix} 4 & 3 & 2 \\ 5 & 1 & 5 \\ 5 & 1 & 2 \end{pmatrix}$

**Solution**

$$ \begin{align*}
    & \left( \begin{array}{ccc|ccc}
        4 & 3 & 2 & 1 & 0 & 0 \\ 
        5 & 1 & 5 & 0 & 1 & 0 \\ 
        5 & 1 & 2 & 0 & 0 & 1
    \end{array} \right) 
    \begin{matrix} \frac{1}{4}R_1 \\ \phantom{x} \\ \phantom{x} \end{matrix} \\
    \longrightarrow 
    & \left( \begin{array}{ccc|ccc}
        1 & \frac{3}{4} & \frac{1}{2} & \frac{1}{4} & 0 & 0 \\ 
        0 & -\frac{11}{4} & \frac{5}{2} & -\frac{5}{4} & 1 & 0 \\ 
        0 & -\frac{11}{4} & -\frac{1}{2} & -\frac{5}{4} & 0 & 1
    \end{array} \right) 
    \begin{matrix}  \\ R_2 - 5R_1 \\ R_3 - 5R_1 \end{matrix}
\end{align*} $$

---

$$ \begin{align*}
    \longrightarrow 
    & \left( \begin{array}{ccc|ccc}
        1 & \frac{3}{4} & \frac{1}{2} & \frac{1}{4} & 0 & 0 \\ 
        0 & 1 & -\frac{10}{11} & \frac{5}{11} & -\frac{4}{11} & 0 \\ 
        0 & -\frac{11}{4} & -\frac{1}{2} & -\frac{5}{4} & 0 & 1
    \end{array} \right) 
    \begin{matrix} R_1 - \frac{3}{4}R_2 \\ \\ R_3 + \frac{11}{4}R_2 \end{matrix} \\
    \longrightarrow 
    & \left( \begin{array}{ccc|ccc}
        1 & 0 & \frac{13}{11} & -\frac{1}{11} & \frac{3}{11} & 0 \\ 
        0 & 1 & -\frac{10}{11} & \frac{5}{11} & -\frac{4}{11} & 0 \\ 
        0 & 0 & -3 & 0 & -1 & 1
    \end{array} \right) 
    \begin{matrix}  \\ \\ -\frac{1}{3}R_3 \end{matrix} \\
    \longrightarrow 
    & \left( \begin{array}{ccc|ccc}
        1 & 0 & \frac{13}{11} & -\frac{1}{11} & \frac{3}{11} & 0 \\ 
        0 & 1 & -\frac{10}{11} & \frac{5}{11} & -\frac{4}{11} & 0 \\ 
        0 & 0 & 1 & 0 & \frac{1}{3} & -\frac{1}{3}
    \end{array} \right) 
    \begin{matrix} R_1 - \frac{13{}11}R_3 \\ R_2 + \frac{10}{11} R_3 \\ \phantom{x} \end{matrix} \\
    \longrightarrow 
    & \left( \begin{array}{ccc|ccc}
        1 & 0 & 0 & -\frac{1}{11} & -\frac{4}{33} & \frac{13}{33} \\ 
        0 & 1 & 0 & \frac{5}{11} & -\frac{2}{33} & -\frac{10}{33} \\ 
        0 & 0 & 1 & 0 & \frac{1}{3} & -\frac{1}{3}
    \end{array} \right)
\end{align*} $$

---
So $A^{-1} = \begin{pmatrix} -\frac{1}{11} & -\frac{4}{33} & \frac{13}{33} \\ \frac{5}{11} & -\frac{2}{33} & -\frac{10}{33} \\ 0 & \frac{1}{3} & -\frac{1}{3} \end{pmatrix}$

Checking this is correct

$$ \begin{align*}
    AA^{-1} &= 
    \begin{pmatrix} 
        4 & 3 & 2 \\ 
        5 & 1 & 5 \\ 
        5 & 1 & 2
    \end{pmatrix}
    \begin{pmatrix} 
        -\frac{1}{11} & -\frac{4}{33} & \frac{13}{33} \\ 
        \frac{5}{11} & -\frac{2}{33} & -\frac{10}{33} \\ 
        0 & \frac{1}{3} & -\frac{1}{3} 
    \end{pmatrix}
    =
    \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}
\end{align*} $$